### ISSUE TITLE
Allow customizing operation expiration on per-operation basis

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#616] opened 2019-08-30 11:31 UTC

**Comment by romanstrobl** [comment] 2020-01-02 15:38
Allow to set the expiration when new operation is created.

**Comment by romanstrobl** [comment] 2021-03-26 11:15
This issue is required for delivering the Next Step master of identity functionality. After giving it another thought, I suggest to store the expiration time in table `ns_operation_config`. We can also add the expiration time into the create operation request later, but at this point I think that configuration in the database is sufficient.

**Comment by romanstrobl** [comment] 2021-03-31 12:15
The issue is fixed in branch https://github.com/wultra/powerauth-webflow/tree/feature/next-step-identity-2 and will be delivered with the next pull request for Next Step identity functionality.

**Closed by romanstrobl** 2021-03-31 12:15 UTC
Labels: enhancement
