### ISSUE TITLE
Correct the documentation regarding setting the limit for the credential usage

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-webflow#1305] opened 2023-05-19 11:48 UTC
According to the [documentation of credential policy configuration](https://developers.wultra.com/components/powerauth-webflow/develop/documentation/Configuring-Next-Step.html#configuration-of-next-step-credential-policies), setting `limit_soft` and `limit_hard` to 0 disable the respective limit. This is not correct. 

Please update the documentation.

**Comment by romanstrobl** [comment] 2023-05-19 11:49
Duplicate of https://github.com/wultra/powerauth-webflow/issues/1304

**Closed by romanstrobl** 2023-05-19 11:49 UTC
Labels: bug
